name: jufs
favicon: null
layout_spectrum: 0.7082018668297678
typography_spectrum: 0.9329236201010644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7850407150108367
  lightness: 0.42292526783421636
  saturation: 0.3301170903723687
  rhythmicContrast: 0.9751859670504928
purpose: []
